# Use Python base image
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /app

# Copy only requirements file first
COPY config/requirements.txt /app/config/requirements.txt

# Install dependencies
RUN pip install --no-cache-dir -r config/requirements.txt

# Copy the rest of the application code
COPY . /app

# Run the pipeline and save artifacts to the local filesystem
CMD ["python", "pipeline_log.py"]